version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/audioGuideServer
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ec2-user