name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: backup existing uploads folder 
      run: mv uploads/ uploads_tmp/
    - uses: actions/checkout@v3
    - name: restore folder 
      run: mv uploads_tmp/ uploads/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Deploy Remaining Files
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
    - run: pm2 restart server