name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
      # Ensure that the directory for uploaded files exists
      sudo mkdir -p /uploads

      # Copy the contents of the "uploads" folder to the destination
      sudo cp -r uploads/. /uploads/

      # Create or update the .env file
      touch .env
      echo "${{ secrets.PROD_ENV_FILE }}" >> .envv
    - run: pm2 restart server